name: Alerta para o Discord

on:
  push:
    branches:
      - main

jobs:
  discord-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para o Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"🚀 Novo push no branch main!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
