name: Alerta no Discord

on:
  push:
    branches:
      - main

jobs:
  discord-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Enviar alerta para o Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\": \"🚨 Novo push no repositório por $GITHUB_ACTOR! Veja: $GITHUB_REPOSITORY\"}" \
             $DISCORD_WEBHOOK_URL
